### ISSUE TITLE
Breaks first file opening on the file tree

### ISSUE THREAD

**Issue by ghost** [glitchassassin/Codiad-Active-Markdown-Links#1]
When opening the first file, the contents show up but no tab is created. Opening a second file creates a tab and substitutes the first one.

**Comment by evertton** [comment]
Screen capture of problem: https://github.com/Codiad/Codiad/issues/805.

**Comment by glitchassassin** [comment]
Hi guys,

Thanks for reporting the issue. My apologies for taking so long to get it fixed, I haven't used Codiad in ages and wasn't able to troubleshoot. This patch should solve the issue.
